obj-$(CONFIG_MACH_LGE) += devices_lge.o
obj-$(CONFIG_MACH_LGE) += lge_earjack_debugger.o
obj-$(CONFIG_MACH_DORY) += board-8026-dory.o
obj-$(CONFIG_MACH_DORY) += board-8026-dory-gpiomux.o
obj-$(CONFIG_LGE_BLUETOOTH) += board-8026-dory-rfkill.o
obj-$(CONFIG_LGE_HANDLE_PANIC) += lge_handle_panic.o
