ccflags-$(CONFIG_POWER_SUPPLY_DEBUG) := -DDEBUG

obj-$(CONFIG_BATTERY_ASUS)   	+= axc_chargerfactory.o
obj-$(CONFIG_PM_8921_CHARGER)   	+= axc_PM8921Charger.o
obj-$(CONFIG_SMB_346_CHARGER)   	+= axc_Smb346Charger.o
obj-$(CONFIG_PM_8941_CHARGER)   	+= axc_PM8941Charger.o
obj-$(CONFIG_IDTP9023_CHARGER)   	+= axc_IDTP9023Charger.o
obj-$(CONFIG_BATTERY_ASUS)   	+= axc_DummyCharger.o
obj-$(CONFIG_PM_8226_CHARGER)   	+= axc_PM8226Charger.o

