ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_icp
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_icp/icp_hw/include
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_icp/icp_hw/icp_hw_mgr/include
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_icp/icp_hw/a5_hw
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_icp/fw_inc
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_cpas/include

obj-$(CONFIG_DEF_CAMERA) += a5_dev.o a5_core.o a5_soc.o
