#
# Makefile for the Goodix gt9xx touchscreen driver.
#

obj-$(CONFIG_GT9XX_MMI_TOUCHPANEL_DRIVER)	+= gt9xx.o
#gt915 update file
obj-$(CONFIG_GT9XX_MMI_TOUCHPANEL_UPDATE)	+= gt9xx_update.o
#debug tool
obj-$(CONFIG_GT9XX_MMI_TOUCHPANEL_DEBUG)	+= goodix_tool.o
