ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_smmu/


obj-$(CONFIG_DEF_CAMERA) += cam_cci_dev.o cam_cci_core.o cam_cci_soc.o
obj-$(CONFIG_DEF_CAMERA) += cci_intf.o
