#
# Makefile for the Toshiba NFC I2C drivers.
#

## Compile only the target include Toshiba NFC configure ##

# I2C Driver
obj-$(CONFIG_NFC_T6NE6)  += I2C/
# GPIO Driver
obj-$(CONFIG_NFC_T6NE6) += GPIO/
