motosh-objs := motosh_core.o \
		motosh_flash.o \
		motosh_ioctl.o \
		motosh_irq.o \
		motosh_queue.o \
		motosh_reset.o \
		motosh_wake_irq.o \
		motosh_display.o \
		motosh_time.o \
		motosh_touch.o \
		motosh_antcap.o
obj-$(CONFIG_MMI_HALL_NOTIFICATIONS) += motosh_mmi_notifications.o
obj-$(CONFIG_SENSORS_MOTOSH) += motosh.o
