ccflags-$(CONFIG_POWER_SUPPLY_DEBUG) := -DDEBUG

obj-$(CONFIG_CHARGER_ASUS_FSM)   	+= AXA_Charging_State.o
obj-$(CONFIG_CHARGER_ASUS_FSM)      += AXC_Charging_FSM.o
obj-$(CONFIG_CHARGER_ASUS_FSM)      += AXC_FSM_Stress_Tester.o

