# MMC Sdhci pci host controller platform data
obj-$(subst m,y,$(CONFIG_MMC_SDHCI_PCI))				+= platform_sdhci_pci.o
# USB OTG controller platform data
obj-$(subst m,y,$(CONFIG_USB_PENWELL_OTG))				+= platform_usb_otg.o
obj-$(subst m,y,$(CONFIG_USB_DWC3_OTG))        += platform_usb_otg.o
obj-$(subst m,y,$(CONFIG_SND_INTEL_SST))                                += platform_sst_pci.o
# USB EHCI/SPH controller platform data
obj-$(subst m,y,$(CONFIG_USB_EHCI_HCD_SPH))				+= platform_ehci_sph.o
# Vibra driver platform data
obj-$(subst m,y,$(CONFIG_INPUT_INTEL_MID_VIBRA))                        += platform_mid_vibra.o
obj-$(subst m,y,$(CONFIG_USB_XHCI_HCD))					+= platform_ush_hsic.o
obj-$(subst m,y,$(CONFIG_VIDEO_CSS2600))				+= platform_css2600.o
