ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t
ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t/sensor/cci
obj-$(CONFIG_MSMB_CAMERA_SHAMU_T) += msm_actuator.o
