ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t
ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t/sensor/io
obj-$(CONFIG_MSMB_CAMERA_SHAMU_T) += msm_led_flash.o
obj-$(CONFIG_MSMB_CAMERA_SHAMU_T) += msm_led_trigger.o
obj-$(CONFIG_MSMB_CAMERA_SHAMU_T) += msm_led_i2c_trigger.o
obj-$(CONFIG_MSMB_CAMERA_SHAMU_T) += adp1660.o
obj-$(CONFIG_LEDS_LM3646_SHAMU_T) += lm3646.o
obj-$(CONFIG_MSMB_CAMERA_SHAMU_T) += msm_led_torch.o
