ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_cpas

obj-$(CONFIG_DEF_CAMERA) += cam_cpastop_hw.o
