ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
obj-y += msm_ois.o msm_ois_i2c.o
obj-$(CONFIG_OIS_ROHM_BU24205GWL)  += lgit_ois_rohm.o
obj-$(CONFIG_OIS_ONSEMI_LC898111A) += lgit_ois_onsemi.o
