stml0xx-objs := stml0xx_core.o \
		stml0xx_flash.o \
		stml0xx_ioctl.o \
		stml0xx_irq.o \
		stml0xx_queue.o \
		stml0xx_reset.o \
		stml0xx_wake_irq.o \
		stml0xx_spi.o \
		stml0xx_spi_crc.o
obj-$(CONFIG_SENSORS_SH_AK09912) += stml0xx_akm.o
obj-$(CONFIG_MMI_HALL_NOTIFICATIONS) += stml0xx_mmi_notifications.o
obj-$(CONFIG_SENSORS_STML0XX) += stml0xx.o
