ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t
ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t/sensor/cci
obj-$(CONFIG_MSM_EEPROM_SHAMU_T) += msm_eeprom.o
