KBUILD_CFLAGS   += -Wno-sizeof-pointer-memaccess
#obj-y += 	mp_test/
obj-y += 								ilitek_drv_main.o \
										ilitek_drv_qcom.o \
										ilitek_drv_update.o \
										ilitek_drv_mp_test.o \
										ilitek_drv_parser.o \
