obj-$(CONFIG_MSM_DBA) += msm_dba.o msm_dba_init.o msm_dba_helpers.o msm_dba_debug.o
obj-$(CONFIG_MSM_DBA_ADV7533) += adv7533.o
obj-$(CONFIG_MSM_DBA_DSI_MOD_DISPLAY) += dsi_mod_display.o
obj-$(CONFIG_MSM_DBA_MOT_DBA) += mot_dba.o
clean:
	rm *.o
