ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t
ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t/sensor/io
obj-$(CONFIG_MSMB_CAMERA_SHAMU_T) += msm_isp.o msm_buf_mgr.o msm_isp_util.o msm_isp_axi_util.o msm_isp_stats_util.o
obj-$(CONFIG_MSMB_CAMERA_SHAMU_T) += msm_isp46.o msm_isp44.o msm_isp40.o msm_isp32.o
