obj-$(CONFIG_MACH_MSM8226_SPRAT) += board-8226-sprat.o \
				    board-8226-sprat-param.o \
				    board-8226-sprat-gpiomux.o \
				    clock-8226-sprat.o

obj-$(CONFIG_BT_BCM4334) += board-bluetooth-bcm4334.o
obj-$(CONFIG_BATTERY_ANDROID) += board-crepe-battery.o
obj-$(CONFIG_MUIC_MAX77836) += switch-max77836.o
obj-$(CONFIG_REGULATOR_MAX77836) += sec-regulator-max77836.o
obj-$(CONFIG_SEC_DEBUG) += sec_debug.o
