#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_CORE_MMI) += focaltech_ts.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_UPGRADE_MMI) += focaltech_flash.o

