#
# Makefile for the focaltech touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_CORE_MMI) += focaltech_ts.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_UPGRADE_MMI) += focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_UPGRADE_8716_MMI) += focaltech_upgrade_ft8716.o focaltech_upgrade_idc.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_UPGRADE_5X46_MMI) += focaltech_upgrade_ft5x46.o
obj-$(CONFIG_TOUCHSCREEN_FOCALTECH_UPGRADE_8006U_MMI) += focaltech_upgrade_ft8006u.o

