#ifndef __INTEL_VLV2_GPIO_H__
#define __INTEL_VLV2_GPIO_H__

#define VV_GPIO_BASE		0
#define VV_GPIO_IRQBASE		256

#define VV_NGPIO_SCORE		102
#define VV_NGPIO_NCORE		28
#define VV_NGPIO_SUS		44

#define VV_PMIC_IRQBASE		456
#define VV_PMIC_GPIO_IRQBASE	496
#define VV_PMIC_GPIO_BASE	200

#endif

