ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/sensor/cci
obj-$(CONFIG_MSMB_CAMERA_2016)   += msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_spi.o msm_camera_dt_util.o
