ccflags-$(CONFIG_POWER_SUPPLY_DEBUG) := -DDEBUG

obj-$(CONFIG_TI_GAUGE)      	+= axc_TI_HWgauge_A80.o
obj-$(CONFIG_TI_GAUGE)			+= axc_TI_HWgauge_Update_A80.o
obj-$(CONFIG_BATTERY_ASUS)      += axc_gauge_a66.o
#obj-$(CONFIG_BATTERY_ASUS)      += axc_gauge_p02.o
obj-$(CONFIG_BATTERY_ASUS)      += axc_gaugefactory.o
obj-$(CONFIG_BATTERY_ASUS)      += AXC_CapacityFilter.o
obj-$(CONFIG_BATTERY_ASUS)      += test_gauge.o

