/*
 * Copyright (c) 2009, Intel Corporation.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * Copyright (C) 2004 Red Hat, Inc.  All rights reserved.
 * Copyright (C) 2004 Novell, Inc.  All rights reserved.
 * Copyright (C) 2004 IBM, Inc. All rights reserved.
 * Copyright (C) 2009 Intel Corporation.  All rights reserved.
 *
 * Licensed under the GNU GPL v2.
 *
 * Authors:
 *	Robert Love		<rml@novell.com>
 *	Kay Sievers		<kay.sievers@vrfy.org>
 *	Arjan van de Ven	<arjanv@redhat.com>
 *	Greg Kroah-Hartman	<greg@kroah.com>
 *
 * Notes:
 *      Adapted from existing kobj event socket code to enable
 *      mutlicast usermode communication for gfx driver to mutiple
 *      usermode threads via different socket broadcast groups.
 *      Original kobject uevent code does not allow for different
 *      broadcast groups.  Due to the frequency of usermode events
 *      generated by some gfx subsystems it is necessary to open
 *      a new dedicated socket with multicast group support.  In
 *      the future it is hoped that this code can be removed
 *      and either a new netlink protocol type added for graphics
 *      or conversely to simply enable group routing to be leveraged
 *      on the existing kobject uevent infrastructure.
 */

#include <linux/version.h>
#include <linux/spinlock.h>
#include <linux/string.h>
#include <linux/kobject.h>
#include <linux/module.h>
#include <linux/socket.h>
#include <linux/skbuff.h>
#include <linux/netlink.h>
#include <net/sock.h>
#include "psb_umevents.h"

#define NETLINK_PSB_KOBJECT_UEVENT	31

u64 psb_uevent_seqnum;
char psb_uevent_helper[UEVENT_HELPER_PATH_LEN] = CONFIG_UEVENT_HELPER_PATH;
static DEFINE_SPINLOCK(sequence_lock);
#if defined(CONFIG_NET)
static struct sock *uevent_sock;
#endif

/* the strings here must match the enum in include/linux/kobject.h */
static const char *psb_kobject_actions[] = {
	[KOBJ_ADD] = "add",
	[KOBJ_REMOVE] = "remove",
	[KOBJ_CHANGE] = "change",
	[KOBJ_MOVE] = "move",
	[KOBJ_ONLINE] = "online",
	[KOBJ_OFFLINE] = "offline",
};

/**
 * kobject_action_type - translate action string to numeric type
 *
 * @buf: buffer containing the action string, newline is ignored
 * @len: length of buffer
 * @type: pointer to the location to store the action type
 *
 * Returns 0 if the action string was recognized.
 */
int psb_kobject_action_type(const char *buf, size_t count,
			    enum kobject_action *type)
{
	enum kobject_action action;
	int ret = -EINVAL;

	if (count && (buf[count - 1] == '\n' || buf[count - 1] == '\0'))
		count--;

	if (!count)
		goto out;

	for (action = 0; action < ARRAY_SIZE(psb_kobject_actions); action++) {
		if (strncmp(psb_kobject_actions[action], buf, count) != 0)
			continue;
		if (psb_kobject_actions[action][count] != '\0')
			continue;
		*type = action;
		ret = 0;
		break;
	}
 out:
	return ret;
}

/**
 * psb_kobject_uevent_env - send an uevent with environmental data
 *
 * @action: action that is happening
 * @kobj: struct kobject that the action is happening to
 * @envp_ext: pointer to environmental data
 *
 * Returns 0 if kobject_uevent() is completed with success or the
 * corresponding error when it fails.
 */
int psb_kobject_uevent_env(struct kobject *kobj, enum kobject_action action,
			   char *envp_ext[], int dst_group_id)
{
	struct kobj_uevent_env *env;
	const char *action_string = psb_kobject_actions[action];
	const char *devpath = NULL;
	const char *subsystem;
	struct kobject *top_kobj;
	struct kset *kset;
	const struct kset_uevent_ops *uevent_ops;
	u64 seq;
	int i = 0;
	int retval = 0;

	pr_debug("kobject: '%s' (%p): %s\n",
		 kobject_name(kobj), kobj, __func__);

	/* search the kset we belong to */
	top_kobj = kobj;
	while (!top_kobj->kset && top_kobj->parent)
		top_kobj = top_kobj->parent;

	if (!top_kobj->kset) {
		pr_debug("kobject: '%s' (%p): %s: attempted to send uevent "
			 "without kset!\n", kobject_name(kobj), kobj, __func__);
		return -EINVAL;
	}

	kset = top_kobj->kset;
	uevent_ops = (const struct kset_uevent_ops *)kset->uevent_ops;

	/* skip the event, if uevent_suppress is set */
	if (kobj->uevent_suppress) {
		pr_debug("kobject: '%s' (%p): %s: uevent_suppress "
			 "caused the event to drop!\n",
			 kobject_name(kobj), kobj, __func__);
		return 0;
	}
	/* skip the event, if the filter returns zero. */
	if (uevent_ops && uevent_ops->filter)
		if (!uevent_ops->filter(kset, kobj)) {
			pr_debug("kobject: '%s' (%p): %s: filter function "
				 "caused the event to drop!\n",
				 kobject_name(kobj), kobj, __func__);
			return 0;
		}

	/* originating subsystem */
	if (uevent_ops && uevent_ops->name)
		subsystem = uevent_ops->name(kset, kobj);
	else
		subsystem = kobject_name(&kset->kobj);
	if (!subsystem) {
		pr_debug("kobject: '%s' (%p): %s: unset subsystem caused the "
			 "event to drop!\n", kobject_name(kobj), kobj,
			 __func__);
		return 0;
	}

	/* environment buffer */
	env = kzalloc(sizeof(struct kobj_uevent_env), GFP_KERNEL);
	if (!env)
		return -ENOMEM;

	/* complete object path */
	devpath = kobject_get_path(kobj, GFP_KERNEL);
	if (!devpath) {
		retval = -ENOENT;
		goto exit;
	}

	/* default keys */
	retval = add_uevent_var(env, "ACTION=%s", action_string);
	if (retval)
		goto exit;
	retval = add_uevent_var(env, "DEVPATH=%s", devpath);
	if (retval)
		goto exit;
	retval = add_uevent_var(env, "SUBSYSTEM=%s", subsystem);
	if (retval)
		goto exit;

	/* keys passed in from the caller */
	if (envp_ext) {
		for (i = 0; envp_ext[i]; i++) {
			retval = add_uevent_var(env, "%s", envp_ext[i]);
			if (retval)
				goto exit;
		}
	}

	/* let the kset specific function add its stuff */
	if (uevent_ops && uevent_ops->uevent) {
		retval = uevent_ops->uevent(kset, kobj, env);
		if (retval) {
			pr_debug("kobject: '%s' (%p): %s: uevent() returned "
				 "%d\n", kobject_name(kobj), kobj,
				 __func__, retval);
			goto exit;
		}
	}

	/*
	 * Mark "add" and "remove" events in the object to ensure proper
	 * events to userspace during automatic cleanup. If the object did
	 * send an "add" event, "remove" will automatically generated by
	 * the core, if not already done by the caller.
	 */
	if (action == KOBJ_ADD)
		kobj->state_add_uevent_sent = 1;
	else if (action == KOBJ_REMOVE)
		kobj->state_remove_uevent_sent = 1;

	/* we will send an event, so request a new sequence number */
	spin_lock(&sequence_lock);
	seq = ++psb_uevent_seqnum;
	spin_unlock(&sequence_lock);
	retval = add_uevent_var(env, "SEQNUM=%llu", (unsigned long long)seq);
	if (retval)
		goto exit;

#if defined(CONFIG_NET)
	/* send netlink message */
	if (uevent_sock) {
		struct sk_buff *skb;
		size_t len;

		/* allocate message with the maximum possible size */
		len = strlen(action_string) + strlen(devpath) + 2;
		skb = alloc_skb(len + env->buflen, GFP_KERNEL);
		if (skb) {
			char *scratch;

			/* add header */
			scratch = skb_put(skb, len);
			sprintf(scratch, "%s@%s", action_string, devpath);

			/* copy keys to our continuous event payload buffer */
			for (i = 0; i < env->envp_idx; i++) {
				len = strlen(env->envp[i]) + 1;
				scratch = skb_put(skb, len);
				strcpy(scratch, env->envp[i]);
			}

			NETLINK_CB(skb).dst_group = dst_group_id;
			retval = netlink_broadcast(uevent_sock, skb, 0,
						   dst_group_id, GFP_KERNEL);

			/* ENOBUFS should be handled in userspace */
			if (retval == -ENOBUFS)
				retval = 0;
		} else
			retval = -ENOMEM;
	}
#endif

	/* call psb_uevent_helper, usually only enabled during early boot */
	if (psb_uevent_helper[0]) {
		char *argv[3];

		argv[0] = psb_uevent_helper;
		argv[1] = (char *)subsystem;
		argv[2] = NULL;
		retval = add_uevent_var(env, "HOME=/");
		if (retval)
			goto exit;
		retval = add_uevent_var(env,
					"PATH=/sbin:/bin:/usr/sbin:/usr/bin");
		if (retval)
			goto exit;

		retval = call_usermodehelper(argv[0], argv,
					     env->envp, UMH_WAIT_EXEC);
	}

 exit:
	kfree(devpath);
	kfree(env);
	return retval;
}

/*EXPORT_SYMBOL_GPL(psb_kobject_uevent_env); */

/**
 * psb_kobject_uevent - notify userspace by ending an uevent
 *
 * @action: action that is happening
 * @kobj: struct kobject that the action is happening to
 *
 * Returns 0 if psb_kobject_uevent() is completed with success or the
 * corresponding error when it fails.
 */
int psb_kobject_uevent(struct kobject *kobj, enum kobject_action action,
		       int dst_group_id)
{
	return psb_kobject_uevent_env(kobj, action, NULL, dst_group_id);
}

/*EXPORT_SYMBOL_GPL(psb_kobject_uevent); */

/**
 * psb_add_uevent_var - add key value string to the environment buffer
 * @env: environment buffer structure
 * @format: printf format for the key=value pair
 *
 * Returns 0 if environment variable was added successfully or -ENOMEM
 * if no space was available.
 */
int psb_add_uevent_var(struct kobj_uevent_env *env, const char *format, ...)
{
	va_list args;
	int len;

	if (env->envp_idx >= ARRAY_SIZE(env->envp)) {
		WARN(1, KERN_ERR "psb_add_uevent_var: too many keys\n");
		return -ENOMEM;
	}

	va_start(args, format);
	len = vsnprintf(&env->buf[env->buflen],
			sizeof(env->buf) - env->buflen, format, args);
	va_end(args);

	if (len >= (sizeof(env->buf) - env->buflen)) {
		WARN(1, KERN_ERR "psb_add_uevent_var: buffer size too small\n");
		return -ENOMEM;
	}

	env->envp[env->envp_idx++] = &env->buf[env->buflen];
	env->buflen += len + 1;
	return 0;
}

/*EXPORT_SYMBOL_GPL(psb_add_uevent_var);*/

#if defined(CONFIG_NET)
int __init psb_kobject_uevent_init(void)
{
	/* This should be the 15, but 3 seems to work better.  Why? WHY!? */
	/* uevent_sock = netlink_kernel_create(&init_net,
	   NETLINK_PSB_KOBJECT_UEVENT,
	   DRM_GFX_SOCKET_GROUPS,
	   NULL, NULL, THIS_MODULE); */

#if (LINUX_VERSION_CODE < KERNEL_VERSION(3,8,0))
	uevent_sock = netlink_kernel_create(&init_net, NETLINK_PSB_KOBJECT_UEVENT, 0x3,	/* 3 is for hotplug & dpst */
					    NULL, NULL, THIS_MODULE);
#else
	struct netlink_kernel_cfg netlnk_cfg;
	memset(&netlnk_cfg, 0, sizeof(struct netlink_kernel_cfg));
	netlnk_cfg.groups = 0x3;
	netlnk_cfg.flags = NL_CFG_F_NONROOT_RECV;
	uevent_sock = netlink_kernel_create(&init_net, NETLINK_PSB_KOBJECT_UEVENT,
						&netlnk_cfg);
#endif
	if (!uevent_sock) {
		printk(KERN_ERR "psb_kobject_uevent: failed create socket!\n");
		return -ENODEV;
	}
#if (LINUX_VERSION_CODE < KERNEL_VERSION(3,8,0))
	netlink_set_nonroot(NETLINK_PSB_KOBJECT_UEVENT, NL_NONROOT_RECV);
#endif
	return 0;
}

#ifndef MODULE
postcore_initcall(psb_kobject_uevent_init);
#endif

#endif
