#ifndef __CAM_GT9767_RECOVERY_H__
#define __CAM_GT9767_RECOVERY_H__
#include <linux/ioctl.h>
#include <linux/videodev2.h>

#define CAM_GT9767_RECOVERY_READ \
	_IOWR('X', BASE_VIDIOC_PRIVATE + 50, int)
#define CAM_GT9767_RECOVERY_READ32 \
	_IOWR('X', BASE_VIDIOC_PRIVATE + 50, int)

#define CAM_GT9767_RECOVERY_WRITE \
	_IOWR('X', BASE_VIDIOC_PRIVATE + 51, int)
#define CAM_GT9767_RECOVERY_WRITE32 \
	_IOWR('X', BASE_VIDIOC_PRIVATE + 51, int)

#define CAM_GT9767_RECOVERY_INIT \
	_IOWR('X', BASE_VIDIOC_PRIVATE + 52, int)
#define CAM_GT9767_RECOVERY_INIT32 \
	_IOWR('X', BASE_VIDIOC_PRIVATE + 52, int)

#define CAM_GT9767_RECOVERY_RELEASE \
	_IOWR('X', BASE_VIDIOC_PRIVATE + 53, int)
#define CAM_GT9767_RECOVERY_RELEASE32 \
	_IOWR('X', BASE_VIDIOC_PRIVATE + 53, int)
#endif
