ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sensor_module/cam_res_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_smmu/

obj-$(CONFIG_DEF_CAMERA) += cam_ir_led_dev.o cam_ir_led_soc.o cam_ir_led_core.o
