ccflags-y += -Idrivers/media/platform/msm/camera_def
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_hyp_intf
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_utils
obj-$(CONFIG_DEF_CAMERA) += cam_hyp_intf.o
