#
# Copyright (C) 2009 Motorola, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# Motorola 2009-Mar-13 - Initial Creation
#
MODULE_NAME = sec

obj-$(CONFIG_SEC_DRIVER) += $(MODULE_NAME).o

$(MODULE_NAME)-objs := sec_core.o
