/*
 * Copyright (c) 2013, Motorola, Inc. All Rights Reserved.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

/*****************************  WARNING  ******************************
 *                                                                    *
 *                        DO NOT EDIT THIS FILE                       *
 *                                                                    *
 *  This is an auto-generated file based on register maps in the      *
 *  M4 Sensor Hub source tree.                                        *
 *                                                                    *
 *****************************  WARNING  *****************************/

enum m4sensorhub_type {
	M4SH_TYPE_ACCEL,
	M4SH_TYPE_TEMP,
	M4SH_TYPE_GENERAL,
	M4SH_TYPE_PRESSURE,
	M4SH_TYPE_PEDOMETER,
	M4SH_TYPE_TCMD,
	M4SH_TYPE_LOG,
	M4SH_TYPE_FUSION,
	M4SH_TYPE_COMPASS,
	M4SH_TYPE_GYRO,
	M4SH_TYPE_METS,
	M4SH_TYPE_USERSETTINGS,
	M4SH_TYPE_POWER,
	M4SH_TYPE_LOCATION,
	M4SH_TYPE_DOWNLOAD,
	M4SH_TYPE_AUDIO,
	M4SH_TYPE_TIMEPIECE,
	M4SH_TYPE_WRIST,
	M4SH_TYPE_GESTURE,
	M4SH_TYPE_PASSIVE,
	M4SH_TYPE_EMG,
	M4SH_TYPE_HEARTRATE,
	M4SH_TYPE_HRSENSOR,
	M4SH_TYPE_LIGHTSENSOR,
	M4SH_TYPE_DEBUG,

	M4SH_TYPE__NUM
};

