ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_req_mgr

obj-$(CONFIG_DEF_CAMERA) += cam_cdm_soc.o cam_cdm_util.o cam_cdm_intf.o \
				cam_cdm_core_common.o cam_cdm_virtual_core.o \
				cam_cdm_hw_core.o
