ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/sensor/cci
obj-$(CONFIG_MSMB_CAMERA_2016) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
