ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_isp/isp_hw_mgr/include
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_cdm/

obj-$(CONFIG_DEF_CAMERA) += isp_hw_mgr/
obj-$(CONFIG_DEF_CAMERA) += cam_isp_dev.o cam_isp_context.o
