ccflags-$(CONFIG_POWER_SUPPLY_DEBUG) := -DDEBUG
obj-$(CONFIG_BATTERY_ASUS)      += axc_cap_filter_a66.o
obj-$(CONFIG_BATTERY_ASUS)      += axc_cap_filter_p02.o
obj-$(CONFIG_BATTERY_ASUS)      += axc_cap_filter_dock.o
obj-$(CONFIG_BATTERY_ASUS)      += axc_cap_filter_factory.o
