ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_2016/sensor/io
obj-$(CONFIG_MSMB_CAMERA_2016) += msm_flash.o
