ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_cdm
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_lrme
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_lrme/lrme_hw_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_lrme/lrme_hw_mgr/lrme_hw
ccflags-y += -Idrivers/media/platform/msm/camera_def0
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_cpas/include

obj-$(CONFIG_DEF_CAMERA) += cam_lrme_hw_dev.o cam_lrme_hw_core.o cam_lrme_hw_soc.o
