ccflags-$(CONFIG_POWER_SUPPLY_DEBUG) := -DDEBUG

obj-$(CONFIG_ASUS_POWER_UTIL)   	+= AXC_DoitLater_OneShotWorker.o
obj-$(CONFIG_ASUS_POWER_UTIL)   	+= AXC_DoitLaterFactory.o
obj-$(CONFIG_ASUS_POWER_UTIL)   	+= AXC_FeedingFileInputTest.o
