obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) += cyttsp5_i2c.o
obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) += cyttsp5_loader.o
obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) += cyttsp5_core.o
obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) += cyttsp5_mt_common.o
obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) += cyttsp5_samsung_factory.o
obj-$(CONFIG_TOUCHSCREEN_CYTTSP5) += cyttsp5_device_access.o
