ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_icp
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_icp/icp_hw/include
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_icp/icp_hw/icp_hw_mgr/include
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_icp/icp_hw/bps_hw
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_icp/fw_inc
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_cpas/include

obj-$(CONFIG_DEF_CAMERA) += bps_dev.o bps_core.o bps_soc.o
