#ccflags-y += -D QUALCOMM_SMB1357
ccflags-y += -D DONGLE_CABLE_INSERT=1
#ccflags-y += -D QUICK_CHARGE_SUPPORT

obj-$(CONFIG_SLIMPORT_ANX7816) := slimport.o \
				  slimport_tx_drv.o \
				  slimport_tx_cec.o \
				  quick_charge.o \
				  anx_slimport.o
