ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_cpas/include
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sensor_module/cam_res_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_utils

obj-$(CONFIG_DEF_CAMERA) += cam_actuator_dev.o cam_actuator_core.o cam_actuator_soc.o
