# SPDX-License-Identifier: GPL-2.0
dts-$(CONFIG_ARCH_HISI) += hi3660-hikey960.dts
dts-$(CONFIG_ARCH_HISI) += hi3670-hikey970.dts
dts-$(CONFIG_ARCH_HISI) += hi3798cv200-poplar.dts
dts-$(CONFIG_ARCH_HISI) += hi6220-hikey.dts
dts-$(CONFIG_ARCH_HISI) += hip05-d02.dts
dts-$(CONFIG_ARCH_HISI) += hip06-d03.dts
dts-$(CONFIG_ARCH_HISI) += hip07-d05.dts
