ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_smmu/
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_core

obj-$(CONFIG_DEF_CAMERA) += cam_context.o cam_context_utils.o cam_node.o cam_subdev.o
