ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_utils
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_req_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_core
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_sync
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_smmu
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_cdm
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_fd
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_fd/fd_hw_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_fd/fd_hw_mgr/fd_hw
ccflags-y += -Idrivers/media/platform/msm/camera_def
ccflags-y += -Idrivers/media/platform/msm/camera_def/cam_cpas/include

obj-$(CONFIG_DEF_CAMERA) += fd_hw/
obj-$(CONFIG_DEF_CAMERA) += cam_fd_hw_mgr.o
