obj-$(CONFIG_MODS_USB_EXT_BRIDGE) += usb_ext_bridge.o
obj-$(CONFIG_MODS_CODEC_BUS) += mods_codec_bus.o
obj-$(CONFIG_USB3813) += usb3813_hub.o
obj-$(CONFIG_MODS_MODBUS_SWITCH) += modbus_switch.o
#obj-$(CONFIG_ICE40) += ice40.o
