ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t
ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t/sensor/io
obj-$(CONFIG_MSM_CPP_SHAMU_T) += msm_cpp.o
