obj-$(CONFIG_RAWIO)		+= rawio.o
obj-$(CONFIG_RAWIO_PCI)		+= rawio_pci.o
obj-$(CONFIG_RAWIO_IOMEM)	+= rawio_iomem.o
obj-$(CONFIG_RAWIO_I2C)		+= rawio_i2c.o
obj-$(CONFIG_RAWIO_MSGBUS)	+= rawio_msgbus.o
obj-$(CONFIG_RAWIO_MSR)		+= rawio_msr.o
