ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t/sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v2_shamu_t/sensor/cci
obj-$(CONFIG_MSMB_CAMERA_SHAMU_T)   += msm_camera_io_util.o msm_camera_cci_i2c.o msm_camera_qup_i2c.o msm_camera_i2c_mux.o msm_camera_spi.o msm_camera_dt_util.o
