#
# Makefile for sensorHub drivers.
#

obj-$(CONFIG_SHUB_ML630Q790)	+=	ml630q790.o \
									shub-batching.o \
									shub-input_mcu.o \
									shub-input_exif.o \
									shub-input_common.o \
									shub-spi.o \
									shub-input_acc.o \
									shub-input_gyro.o \
									shub-input_mag.o \
									shub-input_orientation.o \
									shub-input_linear_acc.o \
									shub-input_game_rotation_vec.o \
									shub-input_grav.o \
									shub-input_gyro_uncal.o \
									shub-input_mag_rotation_vec.o \
									shub-input_mag_uncalib.o \
									shub-input_rotation_vec.o \
									shub-input_pedo.o \
									shub-input_pedodect.o \
									shub-input_significant.o \
									shub-input_diag.o
EXTRA_CFLAGS += -Wall

