# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the QRC bus specific drivers.

obj-$(CONFIG_QRC)       +=  qcom-qrc.o
qcom-qrc-y :=  qrc_core.o qrc_uart.o

#ccflags-$(CONFIG_QRC_DEBUG) := -DDEBUG
