obj-$(CONFIG_MACH_APQ8064_FLO) += board-flo.o \
	board-flo-gpiomux.o \
	board-flo-pmic.o \
	board-flo-camera.o \
	board-flo-gpu.o \
	board-flo-regulator.o \
	board-flo-display.o \
	board-flo-storage.o
